# Generated by Django 4.2.5 on 2023-11-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freetalk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(max_length=255)),
                ('chatgpt_response', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
